library(zoo)
options(scipen = 999, digits.secs = 3)

for(bn in 1:base.num){
  
  start.time <- as.POSIXct("2017-11-01 09:45:00.000")
  timestamps.v <- seq(from=as.POSIXct("2017-11-01 09:45:00.000"),by=.0250,length.out =96000)
  timestamps.v <- timestamps.v + .0001
  # data frame that will contain base series (time, price) pair
  base.sim.df <- data.frame(time=as.character.Date(timestamps.v), price=rep(NA,96000))
  
  # base series jump
  b.jump <- FALSE

  filename = 'file.to.check'
  
  result <- PROP_engine_function_EXT(filename)

  unit.df <- read.table(filename, sep = '\t', dec = '.', skip = 1)
  colnames(unit.df) <- c('timestamp','price')
  
  # base series plot
  plot(unit.df$price, col="blue", type="p", xlab = "time", ylab = "price")
  
  jump.t.df <- read.table(file = "unique")
  
  for(i in 1:nrow(jump.t.df)){

    base.sim.df$price <- NA
    
    # jump sequences
    left.seq <- rev(seq(from=jump.t.df[i,]$li, by=-jump.t.df[i,]$ls/48000,length.out = 48000))
    right.seq <- rev(seq(to=jump.t.df[i,]$ri, by=-jump.t.df[i,]$rs/48000,length.out = 48000))
    
    # adaptive staircase module
    mul.f <- astaircase(base.sim.df, unit.df, left.seq, right.seq)
    
    base.sim.df[base.sim.df$time %in% unit.df$timestamp,]$price <- unit.df$price
    
    # base series and jump sequence multiplied with value generated by adaptive staircase
    base.sim.df$price[1:48000] <- base.sim.df$price[1:48000] + (left.seq * (mul.f))
    base.sim.df$price[48001:96000] <- base.sim.df$price[48001:96000] + (right.seq * (mul.f))
    
    p2 <- paste(i,jump.t.df[i,]$ls,jump.t.df[i,]$rs, jump.t.df[i,]$li,jump.t.df[i,]$ri, mul.f, sep = '_')
    p2 <- paste(p2, "png", sep=".")
    
    setwd('OUTPUT')
    png(filename = p2)
    par(mar=c(4.1, 4.1, 4.1, 6.1), xpd=TRUE, col="darkgreen")
    
    # interpolated time series plot
    plot(na.locf(base.sim.df$price), col="brown", type="l", xlab = "time", ylab = "price")
    
    # adding jump template to the plot
    final <- rep(NA,96000)
    final[1:48000] <- left.seq
    final[48001:96000] <- right.seq
    lines(final+30, col="darkgreen", type = "l")
    # ggplot(base.sim.df, aes(x=time, y=price)) + geom_line() + xlab("time") + ylab("price")
 
    p3 <- c(paste('No',i,sep = ':'),paste('left_slp',jump.t.df[i,]$ls,sep = ':'),paste('right_slp',jump.t.df[i,]$rs,sep = ':'),
            paste('left_int',jump.t.df[i,]$li,sep = ':'),paste('right_int',jump.t.df[i,]$ri,sep = ':'),paste('mul',mul.f,sep = ':'))
    
    legend(x = 96000, y= max(base.sim.df$price, na.rm = T), xpd = TRUE, legend = p3, title = "param", bty = 'n')
    dev.off()
    setwd('../..')
    }
}

jam <- function(filename){
  prog="EXT_PERL_SH.pl"
  cmd = paste("perl",prog,"-s","<",filename,sep=" ")
  x = system(cmd, intern = T)
  x = strsplit(x[2], split = ' ')
  return(x[[1]][1])
}

astaircase <- function(base.simulation, unit.df, left.sim.seq, right.sim.seq,
                       perlfile.path = getwd(),adaptive.output.path = getwd()){
  
  # value to start staircase module
  multiplication.factor = 1
  # track jump->no jump and no jump-> jump changes
  oscillation.f <- 0
  change.factor = 0.25
  
  setwd(perlfile.path)
  adaptive <- data.frame(mfactor=as.numeric(1.000),jumpoutput="nojump",stringsAsFactors=FALSE, oscillationcounter= as.numeric(0), change.factor=as.numeric(0))
  t <- 1
  
  while(TRUE){
    
    adaptive[t+1,]$mfactor <- multiplication.factor
    
    base.simulation[base.simulation$time %in% unit.df$timestamp,]$price <- unit.df$price
    
    base.simulation$price[1:48000] <- base.simulation$price[1:48000] + (left.sim.seq * (multiplication.factor))
    base.simulation$price[48001:96000] <- base.simulation$price[48001:96000] + (right.sim.seq * (multiplication.factor))
    
    new.sim.df <- base.simulation[!is.na(base.simulation$price),]
    
    t.filename <- "out"
    write('171101100500000', file = t.filename)
    write.table(new.sim.df, t.filename, row.names = F, col.names = F, sep='\t', quote = F, append = T)
    t.result <- jam(t.filename)
    
    adaptive[t+1,]$jumpoutput <- t.result
    
    # divide change factor after every swing in oscillation
    if(adaptive$jumpoutput[t+1] != adaptive$jumpoutput[t]){
      oscillation.f <- oscillation.f + 1
      change.factor <- change.factor/2
    }
    
    adaptive[t+1,]$oscillationcounter <- oscillation.f
    adaptive[t+1,]$change.factor <- change.factor
    
    if( t.result =="nojump"){
      multiplication.factor <- round(multiplication.factor * (1 + change.factor),3)
    }else{
      multiplication.factor <- round(multiplication.factor * (1 - change.factor),3)
    }
    
    # flush base series values
    base.simulation$price <- NA
    
    if(nrow(adaptive)>2){
      if(any(nrow(adaptive)>50, abs(adaptive[t,]$mfactor-adaptive[t+1,]$mfactor) <= 0.001,
             multiplication.factor > 30 & (adaptive[t+1,]$jumpoutput == "nojump"))){
        break
      }
    }
    t <- t + 1
    
  }
  
  multiplication.factor <- tail(adaptive[adaptive$jumpoutput=="nojump",]$mfactor, 1)
  return(multiplication.factor)
}
